apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: menu-web
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: gator-bites
spec:
  source:
    git:
      url: https://github.com/aullom1/menu-web
      ref:
        branch: main
